function initGate = initialGate()

	initGate.Ndim = 9;
	initGate.NPoints  = 6;
	initGate.useDim = [0 0 0 0 0 0 0 0 0];
	initGate.timeScaleRange = [.5 8]; 
	initGate.boundaryValues = [-25 25;...
							  -2.5 2.5;...
							   -40 40;...
							   -15 15;...
							    -1  1;...
								-1  1;...
							   -20 20;...
							   -15 30;...
						       -20 20];
	

	for dimN = 1:initGate.Ndim
		initGate.C(dimN,1:initGate.NPoints) = mean(initGate.boundaryValues(dimN,:));
		initGate.W(dimN,1:initGate.NPoints) = (initGate.boundaryValues(dimN,2) - ...
											   initGate.boundaryValues(dimN,1))./2;
	end
	initGate.tau = 2;
	
    
